In [1]:
import polars as pl
import json

pathologies_path = r'C:\Users\Jacey Ong\Documents\Personal Stuff\Coding Projects\Automated Differential Diagnosis via Information Theory\ddx_plus_english\release_conditions.json'

with open(pathologies_path) as f:
    data = json.load(f)

pathologies_json =[]

for _, val in data.items():
    pathologies_json.append({
        'pathology': val.get('condition_name'),
        'icd10_id': val.get('icd10-id'),
        'symptoms': val.get('symptoms'),
        'antecedents': val.get('antecedents'),
        'severity': val.get('severity')
    })

for pathology in pathologies_json:
    symptoms = []
    antecedents = []
    for s, val in pathology['symptoms'].items():
        symptoms.append(s)
    for a, val in pathology['antecedents'].items():
        antecedents.append(a)

    pathology['symptoms'] = symptoms
    pathology['antecedents'] = antecedents

pathologies_json

pathologies_df = pl.DataFrame(pathologies_json)

In [2]:
pathology = pathologies_df.select(['pathology','icd10_id','severity'])
pathology

shape: (49, 3)
┌──────────────────────────┬──────────┬──────────┐
│ pathology                ┆ icd10_id ┆ severity │
│ ---                      ┆ ---      ┆ ---      │
│ str                      ┆ str      ┆ i64      │
╞══════════════════════════╪══════════╪══════════╡
│ Spontaneous pneumothorax ┆ J93      ┆ 2        │
│ Cluster headache         ┆ g44.009  ┆ 3        │
│ Boerhaave                ┆ K22.3    ┆ 2        │
│ Spontaneous rib fracture ┆ S22.9    ┆ 3        │
│ GERD                     ┆ K21      ┆ 3        │
│ …                        ┆ …        ┆ …        │
│ Possible NSTEMI / STEMI  ┆ I21      ┆ 1        │
│ Sarcoidosis              ┆ d86      ┆ 4        │
│ Pancreatic neoplasm      ┆ c25      ┆ 3        │
│ Acute pulmonary edema    ┆ J81.0    ┆ 1        │
│ Pericarditis             ┆ I30      ┆ 4        │
└──────────────────────────┴──────────┴──────────┘

In [20]:
from sqlalchemy import create_engine 
# need to pip install mysql-connector-python first in terminal

user = "root"
password = "root"
host = "127.0.0.1"
port = 3306
database = "ddxplus_db"

url = f"mysql://{user}:{password}@{host}:{port}/{database}"

engine = create_engine(url)

In [51]:
pathology.write_database(
    table_name='pathology_tbl',
    connection = engine,
    if_table_exists='append',
    engine = 'sqlalchemy'
)

49

In [3]:
pathology_evidences = pathologies_df.select(['pathology','symptoms','antecedents'])
pathology_evidences = pathology_evidences.with_columns(pl.concat_list('symptoms','antecedents').alias('evidence')).drop('symptoms','antecedents')
pathology_evidences = pathology_evidences.explode('evidence')
pathology_evidences

shape: (888, 2)
┌──────────────────────────┬──────────┐
│ pathology                ┆ evidence │
│ ---                      ┆ ---      │
│ str                      ┆ str      │
╞══════════════════════════╪══════════╡
│ Spontaneous pneumothorax ┆ E_55     │
│ Spontaneous pneumothorax ┆ E_53     │
│ Spontaneous pneumothorax ┆ E_57     │
│ Spontaneous pneumothorax ┆ E_54     │
│ Spontaneous pneumothorax ┆ E_59     │
│ …                        ┆ …        │
│ Pericarditis             ┆ E_66     │
│ Pericarditis             ┆ E_155    │
│ Pericarditis             ┆ E_0      │
│ Pericarditis             ┆ E_3      │
│ Pericarditis             ┆ E_204    │
└──────────────────────────┴──────────┘

In [64]:
pathology_evidences.write_database(
    table_name='pathology_evidences_tbl',
    connection = engine,
    if_table_exists='append',
    engine = 'sqlalchemy'
)

888

In [4]:
evidences_path = r'C:\Users\Jacey Ong\Documents\Personal Stuff\Coding Projects\Automated Differential Diagnosis via Information Theory\ddx_plus_english\release_evidences.json'

with open(evidences_path) as f:
    evidences_raw = json.load(f)

evidences_json = []

for _, val in evidences_raw.items():
    evidences_json.append(
        {
            'evidence_code': val.get('name'),
            'root_evidence': val.get('code_question'),
            'question': val.get('question_en'),
            'is_antecedent': val.get('is_antecedent'),
            'evidence_type': val.get('data_type'),
            'default_value': val.get('default_value'),
            'possible_values': val.get('possible-values'),
            'value_meaning': val.get('value_meaning')
        }
    )

evidences_df = pl.DataFrame(evidences_json)
evidences_df

shape: (223, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ evidence_c ┆ root_evide ┆ question   ┆ is_antece ┆ evidence_ ┆ default_v ┆ possible_ ┆ value_mea │
│ ode        ┆ nce        ┆ ---        ┆ dent      ┆ type      ┆ alue      ┆ values    ┆ ning      │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ bool      ┆ str       ┆ str       ┆ list[str] ┆ struct[18 │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 8]        │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ E_91       ┆ E_91       ┆ Do you     ┆ false     ┆ B         ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ have a     ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ fever      ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ (either    ┆           ┆           ┆           ┆           ┆ ull…      │
│            ┆            ┆ fe…        ┆           ┆           ┆           ┆           ┆           │
│ E_55       ┆ E_53       ┆ Do you     ┆ false     ┆ M         ┆ V_123     ┆ ["V_123", ┆ {{"nulle  │
│            ┆            ┆ feel pain  ┆           ┆           ┆           ┆ "V_14", … ┆ part","no │
│            ┆            ┆ somewhere? ┆           ┆           ┆           ┆ "V_197"]  ┆ where"},{ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ "ai…      │
│ E_53       ┆ E_53       ┆ Do you     ┆ false     ┆ B         ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ have pain  ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ somewhere, ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ re…        ┆           ┆           ┆           ┆           ┆ ull…      │
│ E_57       ┆ E_53       ┆ Does the   ┆ false     ┆ M         ┆ V_123     ┆ ["V_123", ┆ {{"nulle  │
│            ┆            ┆ pain       ┆           ┆           ┆           ┆ "V_14", … ┆ part","no │
│            ┆            ┆ radiate to ┆           ┆           ┆           ┆ "V_197"]  ┆ where"},{ │
│            ┆            ┆ anoth…     ┆           ┆           ┆           ┆           ┆ "ai…      │
│ E_54       ┆ E_53       ┆ Characteri ┆ false     ┆ M         ┆ V_11      ┆ ["V_11",  ┆ {null,nul │
│            ┆            ┆ ze your    ┆           ┆           ┆           ┆ "V_71", … ┆ l,null,nu │
│            ┆            ┆ pain:      ┆           ┆           ┆           ┆ "V_198"]  ┆ ll,null,n │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ ull…      │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ E_195      ┆ E_195      ┆ Do you     ┆ true      ┆ B         ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ live in    ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ the        ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ suburbs?   ┆           ┆           ┆           ┆           ┆ ull…      │
│ E_183      ┆ E_183      ┆ Do you     ┆ true      ┆ B         ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ live in a  ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ rural      ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ area?      ┆           ┆           ┆           ┆           ┆ ull…      │
│ E_224      ┆ E_224      ┆ Do you     ┆ true      ┆ B         ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ have       ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ family     ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ members    ┆           ┆           ┆           ┆           ┆ ull…      │
│            ┆            ┆ who…       ┆           ┆           ┆           ┆           ┆           │
│ E_223      ┆ E_223      ┆ Are there  ┆ true      ┆ B         ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ members of ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ your fami… ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ ull…      │
│ E_5        ┆ E_5        ┆ Have you   ┆ true      ┆ B         ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ ever had   ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ fluid in   ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ you…       ┆           ┆           ┆           ┆           ┆ ull…      │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [5]:
evidences_df = evidences_df.with_columns(evidence_type = pl.col('evidence_type').replace({'B':'binary','C':'categorical','M':'multichoice'}))
evidences_df

shape: (223, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ evidence_c ┆ root_evide ┆ question   ┆ is_antece ┆ evidence_ ┆ default_v ┆ possible_ ┆ value_mea │
│ ode        ┆ nce        ┆ ---        ┆ dent      ┆ type      ┆ alue      ┆ values    ┆ ning      │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ bool      ┆ str       ┆ str       ┆ list[str] ┆ struct[18 │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 8]        │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ E_91       ┆ E_91       ┆ Do you     ┆ false     ┆ binary    ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ have a     ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ fever      ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ (either    ┆           ┆           ┆           ┆           ┆ ull…      │
│            ┆            ┆ fe…        ┆           ┆           ┆           ┆           ┆           │
│ E_55       ┆ E_53       ┆ Do you     ┆ false     ┆ multichoi ┆ V_123     ┆ ["V_123", ┆ {{"nulle  │
│            ┆            ┆ feel pain  ┆           ┆ ce        ┆           ┆ "V_14", … ┆ part","no │
│            ┆            ┆ somewhere? ┆           ┆           ┆           ┆ "V_197"]  ┆ where"},{ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ "ai…      │
│ E_53       ┆ E_53       ┆ Do you     ┆ false     ┆ binary    ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ have pain  ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ somewhere, ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ re…        ┆           ┆           ┆           ┆           ┆ ull…      │
│ E_57       ┆ E_53       ┆ Does the   ┆ false     ┆ multichoi ┆ V_123     ┆ ["V_123", ┆ {{"nulle  │
│            ┆            ┆ pain       ┆           ┆ ce        ┆           ┆ "V_14", … ┆ part","no │
│            ┆            ┆ radiate to ┆           ┆           ┆           ┆ "V_197"]  ┆ where"},{ │
│            ┆            ┆ anoth…     ┆           ┆           ┆           ┆           ┆ "ai…      │
│ E_54       ┆ E_53       ┆ Characteri ┆ false     ┆ multichoi ┆ V_11      ┆ ["V_11",  ┆ {null,nul │
│            ┆            ┆ ze your    ┆           ┆ ce        ┆           ┆ "V_71", … ┆ l,null,nu │
│            ┆            ┆ pain:      ┆           ┆           ┆           ┆ "V_198"]  ┆ ll,null,n │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ ull…      │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ E_195      ┆ E_195      ┆ Do you     ┆ true      ┆ binary    ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ live in    ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ the        ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ suburbs?   ┆           ┆           ┆           ┆           ┆ ull…      │
│ E_183      ┆ E_183      ┆ Do you     ┆ true      ┆ binary    ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ live in a  ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ rural      ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ area?      ┆           ┆           ┆           ┆           ┆ ull…      │
│ E_224      ┆ E_224      ┆ Do you     ┆ true      ┆ binary    ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ have       ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ family     ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ members    ┆           ┆           ┆           ┆           ┆ ull…      │
│            ┆            ┆ who…       ┆           ┆           ┆           ┆           ┆           │
│ E_223      ┆ E_223      ┆ Are there  ┆ true      ┆ binary    ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ members of ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ your fami… ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ ull…      │
│ E_5        ┆ E_5        ┆ Have you   ┆ true      ┆ binary    ┆ 0         ┆ []        ┆ {null,nul │
│            ┆            ┆ ever had   ┆           ┆           ┆           ┆           ┆ l,null,nu │
│            ┆            ┆ fluid in   ┆           ┆           ┆           ┆           ┆ ll,null,n │
│            ┆            ┆ you…       ┆           ┆           ┆           ┆           ┆ ull…      │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [6]:
numerical_ev = evidences_df.select(pl.exclude(['possible_values','value_meaning'])).filter(pl.col('evidence_type')=='categorical',~pl.col('default_value').str.contains('V_'))
numerical_ev = numerical_ev.cast({'default_value':pl.Int8})
numerical_ev = numerical_ev.rename({'default_value':'default_value_num'})
numerical_ev

shape: (6, 6)
┌───────────────┬───────────────┬─────────────────┬───────────────┬───────────────┬────────────────┐
│ evidence_code ┆ root_evidence ┆ question        ┆ is_antecedent ┆ evidence_type ┆ default_value_ │
│ ---           ┆ ---           ┆ ---             ┆ ---           ┆ ---           ┆ num            │
│ str           ┆ str           ┆ str             ┆ bool          ┆ str           ┆ ---            │
│               ┆               ┆                 ┆               ┆               ┆ i8             │
╞═══════════════╪═══════════════╪═════════════════╪═══════════════╪═══════════════╪════════════════╡
│ E_59          ┆ E_53          ┆ How fast did    ┆ false         ┆ categorical   ┆ 0              │
│               ┆               ┆ the pain        ┆               ┆               ┆                │
│               ┆               ┆ appear?         ┆               ┆               ┆                │
│ E_56          ┆ E_53          ┆ How intense is  ┆ false         ┆ categorical   ┆ 0              │
│               ┆               ┆ the pain?       ┆               ┆               ┆                │
│ E_58          ┆ E_53          ┆ How precisely   ┆ false         ┆ categorical   ┆ 0              │
│               ┆               ┆ is the pain     ┆               ┆               ┆                │
│               ┆               ┆ loca…           ┆               ┆               ┆                │
│ E_134         ┆ E_129         ┆ How intense is  ┆ false         ┆ categorical   ┆ 0              │
│               ┆               ┆ the pain        ┆               ┆               ┆                │
│               ┆               ┆ caused…         ┆               ┆               ┆                │
│ E_132         ┆ E_129         ┆ Is the rash     ┆ false         ┆ categorical   ┆ 0              │
│               ┆               ┆ swollen?        ┆               ┆               ┆                │
│ E_136         ┆ E_129         ┆ How severe is   ┆ false         ┆ categorical   ┆ 0              │
│               ┆               ┆ the itching?    ┆               ┆               ┆                │
└───────────────┴───────────────┴─────────────────┴───────────────┴───────────────┴────────────────┘

In [7]:
binary_ev = evidences_df.select(pl.exclude(['possible_values','value_meaning'])).filter(evidence_type = 'binary')
binary_ev = binary_ev.cast({'default_value':pl.Int8})
binary_ev = binary_ev.rename({'default_value':'default_value_bool'})
binary_ev

shape: (208, 6)
┌───────────────┬───────────────┬─────────────────┬───────────────┬───────────────┬────────────────┐
│ evidence_code ┆ root_evidence ┆ question        ┆ is_antecedent ┆ evidence_type ┆ default_value_ │
│ ---           ┆ ---           ┆ ---             ┆ ---           ┆ ---           ┆ bool           │
│ str           ┆ str           ┆ str             ┆ bool          ┆ str           ┆ ---            │
│               ┆               ┆                 ┆               ┆               ┆ i8             │
╞═══════════════╪═══════════════╪═════════════════╪═══════════════╪═══════════════╪════════════════╡
│ E_91          ┆ E_91          ┆ Do you have a   ┆ false         ┆ binary        ┆ 0              │
│               ┆               ┆ fever (either   ┆               ┆               ┆                │
│               ┆               ┆ fe…             ┆               ┆               ┆                │
│ E_53          ┆ E_53          ┆ Do you have     ┆ false         ┆ binary        ┆ 0              │
│               ┆               ┆ pain somewhere, ┆               ┆               ┆                │
│               ┆               ┆ re…             ┆               ┆               ┆                │
│ E_159         ┆ E_159         ┆ Did you lose    ┆ false         ┆ binary        ┆ 0              │
│               ┆               ┆ consciousness?  ┆               ┆               ┆                │
│ E_129         ┆ E_129         ┆ Do you have any ┆ false         ┆ binary        ┆ 0              │
│               ┆               ┆ lesions, redne… ┆               ┆               ┆                │
│ E_154         ┆ E_154         ┆ Is your skin    ┆ false         ┆ binary        ┆ 0              │
│               ┆               ┆ much paler than ┆               ┆               ┆                │
│               ┆               ┆ u…              ┆               ┆               ┆                │
│ …             ┆ …             ┆ …               ┆ …             ┆ …             ┆ …              │
│ E_195         ┆ E_195         ┆ Do you live in  ┆ true          ┆ binary        ┆ 0              │
│               ┆               ┆ the suburbs?    ┆               ┆               ┆                │
│ E_183         ┆ E_183         ┆ Do you live in  ┆ true          ┆ binary        ┆ 0              │
│               ┆               ┆ a rural area?   ┆               ┆               ┆                │
│ E_224         ┆ E_224         ┆ Do you have     ┆ true          ┆ binary        ┆ 0              │
│               ┆               ┆ family members  ┆               ┆               ┆                │
│               ┆               ┆ who…            ┆               ┆               ┆                │
│ E_223         ┆ E_223         ┆ Are there       ┆ true          ┆ binary        ┆ 0              │
│               ┆               ┆ members of your ┆               ┆               ┆                │
│               ┆               ┆ fami…           ┆               ┆               ┆                │
│ E_5           ┆ E_5           ┆ Have you ever   ┆ true          ┆ binary        ┆ 0              │
│               ┆               ┆ had fluid in    ┆               ┆               ┆                │
│               ┆               ┆ you…            ┆               ┆               ┆                │
└───────────────┴───────────────┴─────────────────┴───────────────┴───────────────┴────────────────┘

In [8]:
enby_ev = evidences_df.select(pl.exclude(['possible_values','value_meaning'])).filter(pl.col('default_value').str.contains('V_'))
enby_ev = enby_ev.rename({'default_value':'default_value_str'})
enby_ev

shape: (9, 6)
┌───────────────┬───────────────┬─────────────────┬───────────────┬───────────────┬────────────────┐
│ evidence_code ┆ root_evidence ┆ question        ┆ is_antecedent ┆ evidence_type ┆ default_value_ │
│ ---           ┆ ---           ┆ ---             ┆ ---           ┆ ---           ┆ str            │
│ str           ┆ str           ┆ str             ┆ bool          ┆ str           ┆ ---            │
│               ┆               ┆                 ┆               ┆               ┆ str            │
╞═══════════════╪═══════════════╪═════════════════╪═══════════════╪═══════════════╪════════════════╡
│ E_55          ┆ E_53          ┆ Do you feel     ┆ false         ┆ multichoice   ┆ V_123          │
│               ┆               ┆ pain somewhere? ┆               ┆               ┆                │
│ E_57          ┆ E_53          ┆ Does the pain   ┆ false         ┆ multichoice   ┆ V_123          │
│               ┆               ┆ radiate to      ┆               ┆               ┆                │
│               ┆               ┆ anoth…          ┆               ┆               ┆                │
│ E_54          ┆ E_53          ┆ Characterize    ┆ false         ┆ multichoice   ┆ V_11           │
│               ┆               ┆ your pain:      ┆               ┆               ┆                │
│ E_133         ┆ E_129         ┆ Where is the    ┆ false         ┆ multichoice   ┆ V_123          │
│               ┆               ┆ affected region ┆               ┆               ┆                │
│               ┆               ┆ l…              ┆               ┆               ┆                │
│ E_130         ┆ E_129         ┆ What color is   ┆ false         ┆ categorical   ┆ V_11           │
│               ┆               ┆ the rash?       ┆               ┆               ┆                │
│ E_135         ┆ E_129         ┆ Is the lesion   ┆ false         ┆ categorical   ┆ V_10           │
│               ┆               ┆ (or are the     ┆               ┆               ┆                │
│               ┆               ┆ lesi…           ┆               ┆               ┆                │
│ E_131         ┆ E_129         ┆ Do your lesions ┆ false         ┆ categorical   ┆ V_10           │
│               ┆               ┆ peel off?       ┆               ┆               ┆                │
│ E_152         ┆ E_151         ┆ Where is the    ┆ false         ┆ multichoice   ┆ V_123          │
│               ┆               ┆ swelling        ┆               ┆               ┆                │
│               ┆               ┆ located?        ┆               ┆               ┆                │
│ E_204         ┆ E_204         ┆ Have you        ┆ true          ┆ categorical   ┆ V_10           │
│               ┆               ┆ traveled out of ┆               ┆               ┆                │
│               ┆               ┆ the c…          ┆               ┆               ┆                │
└───────────────┴───────────────┴─────────────────┴───────────────┴───────────────┴────────────────┘

In [9]:
evidences = pl.concat([binary_ev, numerical_ev, enby_ev],how='diagonal')
evidences

shape: (223, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ evidence_c ┆ root_evide ┆ question   ┆ is_antece ┆ evidence_ ┆ default_v ┆ default_v ┆ default_v │
│ ode        ┆ nce        ┆ ---        ┆ dent      ┆ type      ┆ alue_bool ┆ alue_num  ┆ alue_str  │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ bool      ┆ str       ┆ i8        ┆ i8        ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ E_91       ┆ E_91       ┆ Do you     ┆ false     ┆ binary    ┆ 0         ┆ null      ┆ null      │
│            ┆            ┆ have a     ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ fever      ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ (either    ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ fe…        ┆           ┆           ┆           ┆           ┆           │
│ E_53       ┆ E_53       ┆ Do you     ┆ false     ┆ binary    ┆ 0         ┆ null      ┆ null      │
│            ┆            ┆ have pain  ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ somewhere, ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ re…        ┆           ┆           ┆           ┆           ┆           │
│ E_159      ┆ E_159      ┆ Did you    ┆ false     ┆ binary    ┆ 0         ┆ null      ┆ null      │
│            ┆            ┆ lose consc ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ iousness?  ┆           ┆           ┆           ┆           ┆           │
│ E_129      ┆ E_129      ┆ Do you     ┆ false     ┆ binary    ┆ 0         ┆ null      ┆ null      │
│            ┆            ┆ have any   ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ lesions,   ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ redne…     ┆           ┆           ┆           ┆           ┆           │
│ E_154      ┆ E_154      ┆ Is your    ┆ false     ┆ binary    ┆ 0         ┆ null      ┆ null      │
│            ┆            ┆ skin much  ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ paler than ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ u…         ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ E_130      ┆ E_129      ┆ What color ┆ false     ┆ categoric ┆ null      ┆ null      ┆ V_11      │
│            ┆            ┆ is the     ┆           ┆ al        ┆           ┆           ┆           │
│            ┆            ┆ rash?      ┆           ┆           ┆           ┆           ┆           │
│ E_135      ┆ E_129      ┆ Is the     ┆ false     ┆ categoric ┆ null      ┆ null      ┆ V_10      │
│            ┆            ┆ lesion (or ┆           ┆ al        ┆           ┆           ┆           │
│            ┆            ┆ are the    ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ lesi…      ┆           ┆           ┆           ┆           ┆           │
│ E_131      ┆ E_129      ┆ Do your    ┆ false     ┆ categoric ┆ null      ┆ null      ┆ V_10      │
│            ┆            ┆ lesions    ┆           ┆ al        ┆           ┆           ┆           │
│            ┆            ┆ peel off?  ┆           ┆           ┆           ┆           ┆           │
│ E_152      ┆ E_151      ┆ Where is   ┆ false     ┆ multichoi ┆ null      ┆ null      ┆ V_123     │
│            ┆            ┆ the        ┆           ┆ ce        ┆           ┆           ┆           │
│            ┆            ┆ swelling   ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ located?   ┆           ┆           ┆           ┆           ┆           │
│ E_204      ┆ E_204      ┆ Have you   ┆ true      ┆ categoric ┆ null      ┆ null      ┆ V_10      │
│            ┆            ┆ traveled   ┆           ┆ al        ┆           ┆           ┆           │
│            ┆            ┆ out of the ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ c…         ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [98]:
evidences.write_database(
    'evidences_tbl',
    if_table_exists='append',
    connection=engine,
    engine = 'sqlalchemy'
)

223

In [52]:
ev_val_df = evidences_df.select(['evidence_code','evidence_type','possible_values'])
ev_val_df = ev_val_df.with_columns(possible_values = pl.when(evidence_type = 'binary').then(pl.lit([0,1]))\
                                   .otherwise(pl.col('possible_values')))
ev_val_df = ev_val_df.explode('possible_values')
ev_val_df = ev_val_df.with_columns(pl.concat_str([pl.col('evidence_code'), pl.col('possible_values')],separator="_@_").alias('evidence_value'))

ev_val_bool = ev_val_df.filter(evidence_type = 'binary')\
                        .cast({'possible_values':pl.Int8}).rename({'possible_values':'possible_values_bool'})
ev_val_num = ev_val_df.filter(pl.col('evidence_type')=='categorical',~pl.col('possible_values').str.contains('V_'))\
            .cast({'possible_values':pl.Int8}).rename({'possible_values':'possible_values_num'})
ev_val_str = ev_val_df.filter(pl.col('possible_values').str.contains('V_')).rename({'possible_values':'possible_values_str'})

In [54]:
ev_val = pl.concat([ev_val_bool, ev_val_num, ev_val_str],how='diagonal') 
ev_val

shape: (1_180, 6)
┌───────────────┬───────────────┬────────────────┬────────────────┬────────────────┬───────────────┐
│ evidence_code ┆ evidence_type ┆ possible_value ┆ evidence_value ┆ possible_value ┆ possible_valu │
│ ---           ┆ ---           ┆ s_bool         ┆ ---            ┆ s_num          ┆ es_str        │
│ str           ┆ str           ┆ ---            ┆ str            ┆ ---            ┆ ---           │
│               ┆               ┆ i8             ┆                ┆ i8             ┆ str           │
╞═══════════════╪═══════════════╪════════════════╪════════════════╪════════════════╪═══════════════╡
│ E_91          ┆ binary        ┆ 0              ┆ E_91_@_0       ┆ null           ┆ null          │
│ E_91          ┆ binary        ┆ 1              ┆ E_91_@_1       ┆ null           ┆ null          │
│ E_53          ┆ binary        ┆ 0              ┆ E_53_@_0       ┆ null           ┆ null          │
│ E_53          ┆ binary        ┆ 1              ┆ E_53_@_1       ┆ null           ┆ null          │
│ E_159         ┆ binary        ┆ 0              ┆ E_159_@_0      ┆ null           ┆ null          │
│ …             ┆ …             ┆ …              ┆ …              ┆ …              ┆ …             │
│ E_204         ┆ categorical   ┆ null           ┆ E_204_@_V_6    ┆ null           ┆ V_6           │
│ E_204         ┆ categorical   ┆ null           ┆ E_204_@_V_7    ┆ null           ┆ V_7           │
│ E_204         ┆ categorical   ┆ null           ┆ E_204_@_V_8    ┆ null           ┆ V_8           │
│ E_204         ┆ categorical   ┆ null           ┆ E_204_@_V_9    ┆ null           ┆ V_9           │
│ E_204         ┆ categorical   ┆ null           ┆ E_204_@_V_13   ┆ null           ┆ V_13          │
└───────────────┴───────────────┴────────────────┴────────────────┴────────────────┴───────────────┘

In [56]:
ev_val.write_database(
    'evidence_values_tbl',
    if_table_exists='append',
    connection=engine,
    engine='sqlalchemy'
)

1180

In [57]:
meaning_dict ={
    'value_str':[],
    'value_meaning':[],
    'associated_evidence':[],
}

for ev in evidences_json:
    if ev['value_meaning'] == {}:
        continue

    for k, v in ev['value_meaning'].items():
        meaning_dict['value_str'].append(k)
        meaning_dict['value_meaning'].append(v['en'])
        meaning_dict['associated_evidence'].append(ev['evidence_code'])

meaning_df = pl.DataFrame(meaning_dict)
meaning_df = meaning_df.unique(maintain_order=True)
meaning_df

shape: (698, 3)
┌───────────┬─────────────────┬─────────────────────┐
│ value_str ┆ value_meaning   ┆ associated_evidence │
│ ---       ┆ ---             ┆ ---                 │
│ str       ┆ str             ┆ str                 │
╞═══════════╪═════════════════╪═════════════════════╡
│ V_123     ┆ nowhere         ┆ E_55                │
│ V_14      ┆ iliac wing(R)   ┆ E_55                │
│ V_15      ┆ iliac wing(L)   ┆ E_55                │
│ V_16      ┆ groin(R)        ┆ E_55                │
│ V_17      ┆ groin(L)        ┆ E_55                │
│ …         ┆ …               ┆ …                   │
│ V_6       ┆ Asia            ┆ E_204               │
│ V_7       ┆ South East Asia ┆ E_204               │
│ V_8       ┆ Caraibes        ┆ E_204               │
│ V_9       ┆ Europe          ┆ E_204               │
│ V_13      ┆ Oceania         ┆ E_204               │
└───────────┴─────────────────┴─────────────────────┘

In [ ]:
value_freq = meaning_df.group_by('value_str').len()
value_freq.filter(pl.col('len') == 1)

shape: (31, 2)
┌───────────┬─────┐
│ value_str ┆ len │
│ ---       ┆ --- │
│ str       ┆ u32 │
╞═══════════╪═════╡
│ V_1       ┆ 1   │
│ V_184     ┆ 1   │
│ V_191     ┆ 1   │
│ V_156     ┆ 1   │
│ V_181     ┆ 1   │
│ …         ┆ …   │
│ V_193     ┆ 1   │
│ V_86      ┆ 1   │
│ V_154     ┆ 1   │
│ V_198     ┆ 1   │
│ V_107     ┆ 1   │
└───────────┴─────┘

In [58]:
meaning_df.write_database(
    'string_values_tbl',
    if_table_exists='append',
    connection=engine,
    engine='sqlalchemy'
)

698

In [16]:
evidences_json[1]['evidence_code']

'E_55'